name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: prod build
      run: |
        ng build --prod --base-href https://zonaib-bokhari.github.io/Design-Library/
    - name: deploy to github pages
      run: |
        ngh -no-silent
