name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - uses: actions/setup-node@master
      with:
          node-version: '10.x'
    - name: change directory
      run: |
        cd FF-Design-Library
        dir
    - name: install
      run: npm install
    - name: prod build
      run: |
        npm run build --prod --base-href https://zonaib-bokhari.github.io/Design-Library/
    - name: deploy to github pages
      run: |
        ngh -no-silent
